<footer class="background--black">
                <div class="content">
                    <div class="footer">
                        <div class="footer__company">
                            <h5>The Outpost</h5>
                            A creative VFX <br> and animation studio
                        </div>
                        <div class="footer__office">
                            <h5>Office</h5>
                            Lauwerecht 12<br />
                            3514 BB Utrecht
                        </div>
                        <div class="footer__contact">
                            <h5>General contact</h5>
                            <a href="tel:0031307116294">+31 30 711 62 94</a> <br>
                            <a href="mailto:info@theoutpost.nl">info@theoutpost.nl</a>
                        </div>
                        <div class="footer__social">
                            <h5>Social</h5>
                            <a href="https://www.facebook.com/studiotheoutpost" target="_blank" rel="noopener">fb.</a>
                            <a href="https://www.instagram.com/studiotheoutpost/?hl=nl" target="_blank"
                                rel="noopener">in.</a>
                            <a href="https://vimeo.com/studiotheoutpost" target="_blank" rel="noopener">vi.</a>
                            <a href="https://www.linkedin.com/company/the-outpost/" target="_blank"
                                rel="noopener">li.</a>
                        </div>
                        <div class="footer__careers">
                            <h5>Careers</h5>
                            <a href="mailto:recruitment@theoutpost.nl">recruitment@theoutpost.nl</a> <br>
                            <a href="https://theoutpost.nl/jobs/" class="link">Careers</a>
                        </div>
                        <div class="footer__copyright">
                            Copyright the Outpost 2021 </div>
                        <div class="footer__privacy">
                            <a href="https://theoutpost.nl/terms-and-conditions/">Terms &amp; Conditions</a>
                        </div>
                        <div class="footer__terms">
                            <a href="https://studionaam.com" target="_blank" rel="noopener">Website by Naam.</a>
                        </div>
                        <div class="footer__languages">
                        </div>
                        <button class="footer__up" onclick="window.scrollToTop()">
                            <span class="arrow footer__up__arrow"></span>
                            <span class="footer__up__text">Fly me to the moon</span>
                        </button>
                    </div>

                </div>
            </footer>
        </div>
    </div>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/jquery-3.5.1.min.js?ver=3.5.1"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/flickity.pkgd.min.js?ver=2.2.0"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/jquery.scrollTo.min.js?ver=2.1.2"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/jquery.localScroll.min.js?ver=2.0.0"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/jquery.easing.min.js?ver=1.4.1"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/modernizr-touch.js?ver=3.6.0"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/select2.min.js?ver=4.0.1"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/mixitup.min.js?ver=3.3.1"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/mixitup-multifilter.min.js?ver=3.3.4"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/player.min.js?ver=2.10.0"></script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/libs/lazysizes.min.js?ver=5.2.0"></script>
    <script type='text/javascript'>
        /* <![CDATA[ */
        var init = { "home_url": "https:\/\/theoutpost.nl" };
/* ]]> */
    </script>
    <script defer="defer"
        src="https://theoutpost.nl/wp-content/themes/outpost/js/dist/init-dist.js?ver=1594221671"></script>
    <script type="text/javascript">(function () {
            var expirationDate = new Date();
            expirationDate.setTime(expirationDate.getTime() + 31536000 * 1000);
            document.cookie = "pll_language=en; expires=" + expirationDate.toUTCString() + "; path=/";
        }());</script>
</body>

</html>

<!-- Dynamic page generated in 0.902 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2021-02-06 07:29:28 -->

<!-- super cache -->